// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnO4vPdFiywMAf-r34IWLh2VhGL5jHtTM',
    appId: '1:793723580629:web:c5ab0e85d177c5ae90f25c',
    messagingSenderId: '793723580629',
    projectId: 'voc-archive',
    authDomain: 'voc-archive.firebaseapp.com',
    storageBucket: 'voc-archive.firebasestorage.app',
    measurementId: 'G-C91N3MCEEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQINK6JXckw5PWkH6wZARVUk_c5SqTzyM',
    appId: '1:793723580629:android:cfc22abacb98012b90f25c',
    messagingSenderId: '793723580629',
    projectId: 'voc-archive',
    storageBucket: 'voc-archive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGsWCBYKkl3BbyTqrNhgpZhUJszM_7n9Q',
    appId: '1:793723580629:ios:c3f2c3ee4a24453890f25c',
    messagingSenderId: '793723580629',
    projectId: 'voc-archive',
    storageBucket: 'voc-archive.firebasestorage.app',
    iosBundleId: 'com.example.vocArchive',
  );
}
